### ISSUE TITLE
[BUG] OpenSearch and Dashboards - User and Groups settings in systemd service file

### ISSUE THREAD

**Issue by skevas** [opensearch-project/ansible-playbook#30] opened 2021-12-19 09:15 UTC
**Describe the bug**

Hard coded user and group in service templates dashboards.service and opensearch.service.

**To Reproduce**

-

**Expected behavior**

Use settings from inventories/opensearch/group_vars/all/all.yml

**Playbook Name**

Opensearch and Dashboards

**Screenshots**

-

**Host/Environment (please complete the following information):**

Any

**Additional context**

-

**Solution**

Add {{ os_group }} to inventories/opensearch/group_vars/all/all.yml and replace constants in service files with {{ os_user }} and {{ os_group }}. Further recommendation: Introduce {{ dashboards_user }} and {{ dashboards_groups }}

**Comment by peterzhuamazon** [comment] 2021-12-21 19:54
@saravanan30erd any thoughts?

**Comment by saravanan30erd** [comment] 2021-12-22 06:00
@skevas yes, we can use variables to provide user & group instead of hardcoded values. I will do it once ubuntu and amazon linux support PR is merged. Also this is enhancement, not a bug.

**Comment by skevas** [comment] 2021-12-22 18:42
This is a bug if you are setting the os_user variable to anything but opensearch. In this case, systemd service will fail with something like "Failed to determine user credentials".

**Comment by saravanan30erd** [comment] 2021-12-22 18:56
@skevas Agree, I completely missed the part that `os_user` used on user creation tasks, and not here. Will fix it.

**Comment by peterzhuamazon** [comment] 2021-12-24 07:45
Changing the label without reading the last two comments, it is `bug` again after all 😅 
@saravanan30erd as discussed the AL2 and Ubuntu changes are in, I will assign you as the owner of this issue for now.

Thanks.

**Closed** 2022-01-20 21:53 UTC
Labels: bug
